// <auto-generated />
using System;
using Conveyor.Batch.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conveyor.Batch.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ConveyorBatchDbContext))]
    [Migration("20260710200539_AddHeartbeat")]
    partial class AddHeartbeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.DeadLetterEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SkipCountAtTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StepName");

                    b.ToTable("batch_dead_letter_entries");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobExecutionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("JobInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobInstanceId");

                    b.ToTable("batch_job_executions");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobInstanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobName");

                    b.ToTable("batch_job_instances");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobLockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LockToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "ParametersJson")
                        .IsUnique();

                    b.ToTable("batch_job_locks");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.StepExecutionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionContextJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("JobExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReadCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RollbackCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SkipCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("WriteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobExecutionId");

                    b.ToTable("batch_step_executions");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobExecutionEntity", b =>
                {
                    b.HasOne("Conveyor.Batch.EntityFrameworkCore.Entities.JobInstanceEntity", "JobInstance")
                        .WithMany("JobExecutions")
                        .HasForeignKey("JobInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobInstance");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.StepExecutionEntity", b =>
                {
                    b.HasOne("Conveyor.Batch.EntityFrameworkCore.Entities.JobExecutionEntity", "JobExecution")
                        .WithMany("StepExecutions")
                        .HasForeignKey("JobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobExecution");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobExecutionEntity", b =>
                {
                    b.Navigation("StepExecutions");
                });

            modelBuilder.Entity("Conveyor.Batch.EntityFrameworkCore.Entities.JobInstanceEntity", b =>
                {
                    b.Navigation("JobExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
